version: '2'

services:
  nginx:
    image: nginx
    depends_on:
      - web
    ports:
      - "8000:80"
    volumes:
      - code:/code
      - nginx.conf:/etc/nginx/conf.d/default.conf

  web:
    image: gewis/gewisweb
    depends_on:
      - webmysql
    volumes:
      - code:/code

  webmysql:
    image: mysql:5.7
    volumes:
      - .mysql/dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: gewis
      MYSQL_DATABASE: gewis
      MYSQL_USER: gewis
      MYSQL_PASSWORD: gewis
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

volumes:
  code:
      external:
          name: gewisweb
